import Head from "next/head";
import styles from "../styles/Home.module.css";
import Categories from "../components/Categories";
import SearchField from "../components/SearchField";
import Cards from "../components/Cards";
import { productsEntrada, filterProduct, searchProduct } from "../services";
import { useState, useEffect } from "react";

export default function Home() {

  const [filteredData, setFilteredData] = useState(productsEntrada)
  const [typedSearchText, setTypedSearchText] = useState("")
  const [buttonClicked, setButtonClicked] = useState("Entradas")

  const handleSearch = (text) => {
    setTypedSearchText(text)
    setButtonClicked("")
    text.length >= 3 && setFilteredData(searchProduct(text))
  }

  const handleFilter = (category) => {
    setTypedSearchText("")
    setFilteredData(filterProduct(category))
    setButtonClicked(category)
  }

  return (
    <>
      <Head>
        <title>Cardápio Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Poppins&display=swap" rel="stylesheet" />
      </Head>
      <main className={styles.main}>
        <div className={styles.banner}>
          <h1>RESTAURANT</h1>
          <p>De pratos clássicos a criações surpreendentes, nosso cardápio é um requinte de sabores refinados.</p>
        </div>
        <Categories handleFilter={handleFilter} typeButtonClicked={buttonClicked} />
        <SearchField handleSearch={handleSearch} typedSearchText={typedSearchText} />
        <h2>Cardápio</h2>
        <div className={styles.cards_container}>
          {filteredData.map((product) => (
            <Cards key={product.id} product={product} />
          ))}
        </div>
      </main>
    </>
  );
}
